### ISSUE TITLE
Akka dispatcher fine tuning

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#64]
The default dispatcher configuration is the root of the message passing stall that can occur during times of high activity.  It has to do with how threads are shared among all the actors.  Configuring actors to have different execution contexts can help with this problem and give more explicit control over how the actor system is handling threading.

This issue will track a long term initiative to fine tune the dispatcher configuration for all actors in the simulation.

**Comment by aaronschutza** [comment]
I think I've found a solution to our performance problems, all I need to do is set the execution context to used pinned dispatchers: https://doc.akka.io/docs/akka/current/typed/dispatchers.html#pinned

What was happening is the default dispatcher config has a fixed number of threads in the dispatcher pool and then a single thread that tells which dispatcher to act on which mailbox. The throughput is 1 so it will process one message and then release the lock on the actor and another dispatcher comes in and acts on the next message when one is available from the pool. The monitor state of the pool dispatcher threads is induced by this waiting for the lock to be released from the previous dispatcher. Since we are not memory constrained there is no purpose to this behavior, and what it was doing was just slowing down mailbox processing during high activity since there were many more mailboxes than there were dispatcher threads. The execution context is set in scorex application.conf settings, and I think my actor system inherited that configuration since I'm starting all simulation actors in that actorSystem. The default config uses a fixed thread pool for actors and that was what was used before. Naturally I hit this overhead limit as the program got more sophisticated over time.

The monitor state of a dispatcher thread (as opposed to parked and running) means it's waiting for a mutex (the lock that prevents other threads from entering a memory space that is being operated on by an active thread). If each mailbox in the system has its own dedicated dispatcher thread, this monitor state would never be incurred and thread allocation to mailboxes wouldn't need to be processed. The trade off is more threads in the JVM but since we have a relatively small number of actors it doesn't make sense to limit the number of dispatchers.

**Comment by aaronschutza** [comment]
file:///tmp/Spectacle.TGjdBj/Screenshot_20200712_091124.png

Thread configuration with PinnedDispatcher, each actor has it's own thread.

**Comment by aaronschutza** [comment]
I was able to reproduce the state that causes the message passing stall.  It has to do with router accessing java uuid generator.  This is a change I made to router to generate uids for all messages.  So when all routers are accessing it at the same time they have to wait, putting it in a monitor state.  The more messages the more access to the uuid method.

"prosomo-params.router-28" #92 prio=5 os_prio=0 tid=0x00007f469400c000 nid=0x1437a2 waiting for monitor entry [0x00007f46821ef000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:215)
        - waiting to lock <0x00000000802da6a8> (a sun.security.provider.SecureRandom)
        at sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:535)
        at sun.security.provider.NativePRNG$RandomIO.access$400(NativePRNG.java:331)
        at sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220)
        at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
        at java.util.UUID.randomUUID(UUID.java:145)
        at prosomo.stakeholder.Router.uuid(Router.scala:104)
        at prosomo.stakeholder.Router$$anonfun$messageFromLocal$1.applyOrElse(Router.scala:814)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at prosomo.stakeholder.Router.akka$actor$Timers$$super$aroundReceive(Router.scala:48)
        at akka.actor.Timers.aroundReceive(Timers.scala:55)
        at akka.actor.Timers.aroundReceive$(Timers.scala:40)
        at prosomo.stakeholder.Router.aroundReceive(Router.scala:48)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x0000000082887b98> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by aaronschutza** [comment]
The bug that was causing message delays and stalling of the monster node has been fixed.  The execution context of each type of actor in the simulation is now specified in application.conf under params.  Each actor now has a dedicated dispatcher thread that processes messages in one inbox.  If the inbox doesn't have any messages the thread is killed and spun back up when another message arrives.
